/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Android android = new Android("Huawei", "Black", "Android");
        Person person = new Person(android, "This is a message");
        person.setName("JAE");

        IPhone iPhone = new IPhone("Huawei", "Black", "iPhone");
        Person otherPerson = new Person(iPhone, "This is a message");
        person.setName("JAEME");

        android.getMobileBasicInfo();
        iPhone.getMobileBasicInfo();
//        IPhoneRobot robot = new IPhoneRobot(android, "Message");
        IPhoneRobot anotherRobot = new IPhoneRobot(iPhone, "Message");
    }
}
